//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.12 at 05:10:52 PM CEST 
//


package ac.at.acdh.x3ml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for source_infoComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="source_infoComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}source_schema"/>
 *         &lt;element name="source_collection" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "source_infoComplexType", propOrder = {
    "sourceSchema",
    "sourceCollection"
})
public class SourceInfoComplexType {

    @XmlElement(name = "source_schema", required = true)
    protected SourceSchema sourceSchema;
    @XmlElement(name = "source_collection", required = true)
    protected String sourceCollection;

    /**
     * Gets the value of the sourceSchema property.
     * 
     * @return
     *     possible object is
     *     {@link SourceSchema }
     *     
     */
    public SourceSchema getSourceSchema() {
        return sourceSchema;
    }

    /**
     * Sets the value of the sourceSchema property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceSchema }
     *     
     */
    public void setSourceSchema(SourceSchema value) {
        this.sourceSchema = value;
    }

    /**
     * Gets the value of the sourceCollection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceCollection() {
        return sourceCollection;
    }

    /**
     * Sets the value of the sourceCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceCollection(String value) {
        this.sourceCollection = value;
    }

}
