//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.12 at 05:10:52 PM CEST 
//


package gr.forth.x3ml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}type" maxOccurs="unbounded"/>
 *         &lt;element ref="{}instance_info" minOccurs="0"/>
 *         &lt;element ref="{}instance_generator" minOccurs="0"/>
 *         &lt;element ref="{}label_generator" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}additional" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="variable" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "type",
    "instanceInfo",
    "instanceGenerator",
    "labelGenerator",
    "additional"
})
@XmlRootElement(name = "entity")
public class Entity {

    @XmlElement(required = true)
    protected List<String> type;
    @XmlElement(name = "instance_info")
    protected InstanceInfo instanceInfo;
    @XmlElement(name = "instance_generator")
    protected InstanceGenerator instanceGenerator;
    @XmlElement(name = "label_generator")
    protected List<LabelGenerator> labelGenerator;
    protected List<Additional> additional;
    @XmlAttribute(name = "variable")
    @XmlSchemaType(name = "anySimpleType")
    protected String variable;
    
    //custom field, seems that old version of x3ml didn't have it
    @XmlAttribute(name = "global_variable")
    protected String globalVariable;

    /**
     * Gets the value of the type property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the type property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getType() {
        if (type == null) {
            type = new ArrayList<String>();
        }
        return this.type;
    }


	/**
     * Gets the value of the instanceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link InstanceInfo }
     *     
     */
    public InstanceInfo getInstanceInfo() {
        return instanceInfo;
    }

    /**
     * Sets the value of the instanceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstanceInfo }
     *     
     */
    public void setInstanceInfo(InstanceInfo value) {
        this.instanceInfo = value;
    }

    /**
     * Gets the value of the instanceGenerator property.
     * 
     * @return
     *     possible object is
     *     {@link InstanceGenerator }
     *     
     */
    public InstanceGenerator getInstanceGenerator() {
        return instanceGenerator;
    }

    /**
     * Sets the value of the instanceGenerator property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstanceGenerator }
     *     
     */
    public void setInstanceGenerator(InstanceGenerator value) {
        this.instanceGenerator = value;
    }

    /**
     * Gets the value of the labelGenerator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the labelGenerator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabelGenerator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LabelGenerator }
     * 
     * 
     */
    public List<LabelGenerator> getLabelGenerator() {
        if (labelGenerator == null) {
            labelGenerator = new ArrayList<LabelGenerator>();
        }
        return this.labelGenerator;
    }

    /**
     * Gets the value of the additional property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additional property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditional().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Additional }
     * 
     * 
     */
    public List<Additional> getAdditional() {
        if (additional == null) {
            additional = new ArrayList<Additional>();
        }
        return this.additional;
    }

    /**
     * Gets the value of the variable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariable() {
        return variable;
    }

    /**
     * Sets the value of the variable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariable(String value) {
        this.variable = value;
    }


	public String getGlobalVariable() {
		return globalVariable;
	}


	public void setGlobalVariable(String globalVariable) {
		this.globalVariable = globalVariable;
	}
    
    

}
