//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.12 at 05:10:52 PM CEST 
//


package gr.forth.x3ml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for exampleComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="exampleComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="example_source" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="example_target" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "exampleComplexType", propOrder = {
    "exampleSource",
    "exampleTarget"
})
public class ExampleComplexType {

    @XmlElement(name = "example_source", required = true)
    protected String exampleSource;
    @XmlElement(name = "example_target", required = true)
    protected String exampleTarget;

    /**
     * Gets the value of the exampleSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExampleSource() {
        return exampleSource;
    }

    /**
     * Sets the value of the exampleSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExampleSource(String value) {
        this.exampleSource = value;
    }

    /**
     * Gets the value of the exampleTarget property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExampleTarget() {
        return exampleTarget;
    }

    /**
     * Sets the value of the exampleTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExampleTarget(String value) {
        this.exampleTarget = value;
    }

}
