//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.12 at 05:10:52 PM CEST 
//


package gr.forth.x3ml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mapping_infoComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mapping_infoComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="mapping_created_by_org" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="mapping_created_by_person" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="in_collaboration_with" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mapping_infoComplexType", propOrder = {
    "mappingCreatedByOrg",
    "mappingCreatedByPerson",
    "inCollaborationWith"
})
public class MappingInfoComplexType {

    @XmlElement(name = "mapping_created_by_org", required = true)
    protected String mappingCreatedByOrg;
    @XmlElement(name = "mapping_created_by_person", required = true)
    protected String mappingCreatedByPerson;
    @XmlElement(name = "in_collaboration_with", required = true)
    protected String inCollaborationWith;

    /**
     * Gets the value of the mappingCreatedByOrg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMappingCreatedByOrg() {
        return mappingCreatedByOrg;
    }

    /**
     * Sets the value of the mappingCreatedByOrg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMappingCreatedByOrg(String value) {
        this.mappingCreatedByOrg = value;
    }

    /**
     * Gets the value of the mappingCreatedByPerson property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMappingCreatedByPerson() {
        return mappingCreatedByPerson;
    }

    /**
     * Sets the value of the mappingCreatedByPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMappingCreatedByPerson(String value) {
        this.mappingCreatedByPerson = value;
    }

    /**
     * Gets the value of the inCollaborationWith property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInCollaborationWith() {
        return inCollaborationWith;
    }

    /**
     * Sets the value of the inCollaborationWith property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInCollaborationWith(String value) {
        this.inCollaborationWith = value;
    }

}
