//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.12 at 05:10:52 PM CEST 
//


package gr.forth.x3ml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the x3ml2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Node_QNAME = new QName("", "node");
    private final static QName _SourceNode_QNAME = new QName("", "source_node");
    private final static QName _Exists_QNAME = new QName("", "exists");
    private final static QName _Relationship_QNAME = new QName("", "relationship");
    private final static QName _Type_QNAME = new QName("", "type");
    private final static QName _TargetNode_QNAME = new QName("", "target_node");
    private final static QName _Relation2_QNAME = new QName("", "relation2");
    private final static QName _If_QNAME = new QName("", "if");
    private final static QName _Relation_QNAME = new QName("", "relation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: x3ml2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InstanceGenerator }
     * 
     */
    public InstanceGenerator createInstanceGenerator() {
        return new InstanceGenerator();
    }

    /**
     * Create an instance of {@link LabelGenerator }
     * 
     */
    public LabelGenerator createLabelGenerator() {
        return new LabelGenerator();
    }

    /**
     * Create an instance of {@link X3ML }
     * 
     */
    public X3ML createX3Ml() {
        return new X3ML();
    }

    /**
     * Create an instance of {@link ConditionsType }
     * 
     */
    public ConditionsType createConditionsType() {
        return new ConditionsType();
    }

    /**
     * Create an instance of {@link X3ML.Mappings }
     * 
     */
    public X3ML.Mappings createX3MlMappings() {
        return new X3ML.Mappings();
    }

    /**
     * Create an instance of {@link X3ML.Mappings.Mapping }
     * 
     */
    public X3ML.Mappings.Mapping createX3MlMappingsMapping() {
        return new X3ML.Mappings.Mapping();
    }

    /**
     * Create an instance of {@link X3ML.Mappings.Mapping.Link }
     * 
     */
    public X3ML.Mappings.Mapping.Link createX3MlMappingsMappingLink() {
        return new X3ML.Mappings.Mapping.Link();
    }

    /**
     * Create an instance of {@link X3ML.Namespaces }
     * 
     */
    public X3ML.Namespaces createX3MlNamespaces() {
        return new X3ML.Namespaces();
    }

    /**
     * Create an instance of {@link TargetSchema }
     * 
     */
    public TargetSchema createTargetSchema() {
        return new TargetSchema();
    }

    /**
     * Create an instance of {@link Additional }
     * 
     */
    public Additional createAdditional() {
        return new Additional();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link InstanceInfo }
     * 
     */
    public InstanceInfo createInstanceInfo() {
        return new InstanceInfo();
    }

    /**
     * Create an instance of {@link InstanceGenerator.Arg }
     * 
     */
    public Arg createInstanceGeneratorArg() {
        return new Arg();
    }

    /**
     * Create an instance of {@link LabelGenerator.Arg }
     * 
     */
    public Arg createLabelGeneratorArg() {
        return new Arg();
    }

    /**
     * Create an instance of {@link ExampleDataSourceRecord }
     * 
     */
    public ExampleDataSourceRecord createExampleDataSourceRecord() {
        return new ExampleDataSourceRecord();
    }

    /**
     * Create an instance of {@link Info }
     * 
     */
    public Info createInfo() {
        return new Info();
    }

    /**
     * Create an instance of {@link SourceInfoComplexType }
     * 
     */
    public SourceInfoComplexType createSourceInfoComplexType() {
        return new SourceInfoComplexType();
    }

    /**
     * Create an instance of {@link TargetInfoComplexType }
     * 
     */
    public TargetInfoComplexType createTargetInfoComplexType() {
        return new TargetInfoComplexType();
    }

    /**
     * Create an instance of {@link MappingInfoComplexType }
     * 
     */
    public MappingInfoComplexType createMappingInfoComplexType() {
        return new MappingInfoComplexType();
    }

    /**
     * Create an instance of {@link ExampleDataInfoComplexType }
     * 
     */
    public ExampleDataInfoComplexType createExampleDataInfoComplexType() {
        return new ExampleDataInfoComplexType();
    }

    /**
     * Create an instance of {@link CommentsType }
     * 
     */
    public CommentsType createCommentsType() {
        return new CommentsType();
    }

    /**
     * Create an instance of {@link RangeTargetNodeType }
     * 
     */
    public RangeTargetNodeType createRangeTargetNodeType() {
        return new RangeTargetNodeType();
    }

    /**
     * Create an instance of {@link CommentsLastUpdate }
     * 
     */
    public CommentsLastUpdate createCommentsLastUpdate() {
        return new CommentsLastUpdate();
    }

    /**
     * Create an instance of {@link ExampleDataTargetRecord }
     * 
     */
    public ExampleDataTargetRecord createExampleDataTargetRecord() {
        return new ExampleDataTargetRecord();
    }

    /**
     * Create an instance of {@link Equals }
     * 
     */
    public Equals createEquals() {
        return new Equals();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link ExampleComplexType }
     * 
     */
    public ExampleComplexType createExampleComplexType() {
        return new ExampleComplexType();
    }

    /**
     * Create an instance of {@link SourceSchema }
     * 
     */
    public SourceSchema createSourceSchema() {
        return new SourceSchema();
    }

    /**
     * Create an instance of {@link TargetRelationType }
     * 
     */
    public TargetRelationType createTargetRelationType() {
        return new TargetRelationType();
    }

    /**
     * Create an instance of {@link DomainTargetNodeType }
     * 
     */
    public DomainTargetNodeType createDomainTargetNodeType() {
        return new DomainTargetNodeType();
    }

    /**
     * Create an instance of {@link SourceRelationType }
     * 
     */
    public SourceRelationType createSourceRelationType() {
        return new SourceRelationType();
    }

    /**
     * Create an instance of {@link ConditionsType.Not }
     * 
     */
    public ConditionsType.Not createConditionsTypeNot() {
        return new ConditionsType.Not();
    }

    /**
     * Create an instance of {@link ConditionsType.And }
     * 
     */
    public ConditionsType.And createConditionsTypeAnd() {
        return new ConditionsType.And();
    }

    /**
     * Create an instance of {@link ConditionsType.Or }
     * 
     */
    public ConditionsType.Or createConditionsTypeOr() {
        return new ConditionsType.Or();
    }

    /**
     * Create an instance of {@link ConditionsType.Narrower }
     * 
     */
    public ConditionsType.Narrower createConditionsTypeNarrower() {
        return new ConditionsType.Narrower();
    }

    /**
     * Create an instance of {@link X3ML.Mappings.Mapping.Domain }
     * 
     */
    public X3ML.Mappings.Mapping.Domain createX3MlMappingsMappingDomain() {
        return new X3ML.Mappings.Mapping.Domain();
    }

    /**
     * Create an instance of {@link X3ML.Mappings.Mapping.Link.Path }
     * 
     */
    public X3ML.Mappings.Mapping.Link.Path createX3MlMappingsMappingLinkPath() {
        return new X3ML.Mappings.Mapping.Link.Path();
    }

    /**
     * Create an instance of {@link X3ML.Mappings.Mapping.Link.Range }
     * 
     */
    public X3ML.Mappings.Mapping.Link.Range createX3MlMappingsMappingLinkRange() {
        return new X3ML.Mappings.Mapping.Link.Range();
    }

    /**
     * Create an instance of {@link X3ML.Namespaces.Namespace }
     * 
     */
    public X3ML.Namespaces.Namespace createX3MlNamespacesNamespace() {
        return new X3ML.Namespaces.Namespace();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "node")
    public JAXBElement<String> createNode(String value) {
        return new JAXBElement<String>(_Node_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "source_node")
    public JAXBElement<String> createSourceNode(String value) {
        return new JAXBElement<String>(_SourceNode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "exists")
    public JAXBElement<String> createExists(String value) {
        return new JAXBElement<String>(_Exists_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "relationship")
    public JAXBElement<String> createRelationship(String value) {
        return new JAXBElement<String>(_Relationship_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RangeTargetNodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "target_node")
    public JAXBElement<RangeTargetNodeType> createTargetNode(RangeTargetNodeType value) {
        return new JAXBElement<RangeTargetNodeType>(_TargetNode_QNAME, RangeTargetNodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "relation2")
    public JAXBElement<String> createRelation2(String value) {
        return new JAXBElement<String>(_Relation2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConditionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "if")
    public JAXBElement<ConditionsType> createIf(ConditionsType value) {
        return new JAXBElement<ConditionsType>(_If_QNAME, ConditionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "relation")
    public JAXBElement<String> createRelation(String value) {
        return new JAXBElement<String>(_Relation_QNAME, String.class, null, value);
    }

}
