//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.12 at 05:10:52 PM CEST 
//


package gr.forth.x3ml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for target_infoComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="target_infoComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}target_schema"/&gt;
 *         &lt;element name="target_collection" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "target_infoComplexType", propOrder = {
    "targetSchema",
    "targetCollection"
})
public class TargetInfoComplexType {

    @XmlElement(name = "target_schema", required = true)
    protected TargetSchema targetSchema;
    @XmlElement(name = "target_collection", required = true)
    protected String targetCollection;

    /**
     * Gets the value of the targetSchema property.
     * 
     * @return
     *     possible object is
     *     {@link TargetSchema }
     *     
     */
    public TargetSchema getTargetSchema() {
        return targetSchema;
    }

    /**
     * Sets the value of the targetSchema property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetSchema }
     *     
     */
    public void setTargetSchema(TargetSchema value) {
        this.targetSchema = value;
    }

    /**
     * Gets the value of the targetCollection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetCollection() {
        return targetCollection;
    }

    /**
     * Sets the value of the targetCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetCollection(String value) {
        this.targetCollection = value;
    }

}
