//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.12 at 05:10:52 PM CEST 
//


package gr.forth.x3ml;

import java.util.ArrayList;
import java.util.List;
import java.util.jar.Attributes.Name;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}info" minOccurs="0"/&gt;
 *         &lt;element name="namespaces"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="namespace" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="prefix" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *                           &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="mappings"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="mapping" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="domain"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element ref="{}source_node"/&gt;
 *                                       &lt;element name="target_node" type="{}domain_target_nodeType"/&gt;
 *                                       &lt;element name="comments" type="{}commentsType" minOccurs="0"/&gt;
 *                                     &lt;/sequence&gt;
 *                                     &lt;attribute name="repeated" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="link" maxOccurs="unbounded" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="path"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="source_relation" type="{}source_relationType"/&gt;
 *                                                 &lt;element name="target_relation" type="{}target_relationType"/&gt;
 *                                                 &lt;element name="comments" type="{}commentsType" minOccurs="0"/&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                       &lt;element name="range"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element ref="{}source_node"/&gt;
 *                                                 &lt;element name="target_node" type="{}range_target_nodeType"/&gt;
 *                                                 &lt;element name="comments" type="{}commentsType" minOccurs="0"/&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="comments" type="{}commentsType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="source_type" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * <pre>
 
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "info",
    "namespaces",
    "mappings",
    "comments"
})
@XmlRootElement(name = "x3ml")
public class X3ML {

    protected Info info;
    @XmlElement(required = true)
    protected X3ML.Namespaces namespaces;
    @XmlElement(required = true)
    protected X3ML.Mappings mappings;
    protected CommentsType comments;
    @XmlAttribute(name = "version", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String version;
    @XmlAttribute(name = "source_type", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String sourceType;

    /**
     * Gets the value of the info property.
     * 
     * @return
     *     possible object is
     *     {@link Info }
     *     
     */
    public Info getInfo() {
        return info;
    }

    /**
     * Sets the value of the info property.
     * 
     * @param value
     *     allowed object is
     *     {@link Info }
     *     
     */
    public void setInfo(Info value) {
        this.info = value;
    }

    /**
     * Gets the value of the namespaces property.
     * 
     * @return
     *     possible object is
     *     {@link X3ML.Namespaces }
     *     
     */
    public X3ML.Namespaces getNamespaces() {
        return namespaces;
    }

    /**
     * Sets the value of the namespaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link X3ML.Namespaces }
     *     
     */
    public void setNamespaces(X3ML.Namespaces value) {
        this.namespaces = value;
    }

    /**
     * Gets the value of the mappings property.
     * 
     * @return
     *     possible object is
     *     {@link X3ML.Mappings }
     *     
     */
    public X3ML.Mappings getMappings() {
        return mappings;
    }

    /**
     * Sets the value of the mappings property.
     * 
     * @param value
     *     allowed object is
     *     {@link X3ML.Mappings }
     *     
     */
    public void setMappings(X3ML.Mappings value) {
        this.mappings = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link CommentsType }
     *     
     */
    public CommentsType getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommentsType }
     *     
     */
    public void setComments(CommentsType value) {
        this.comments = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the sourceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceType() {
        return sourceType;
    }

    /**
     * Sets the value of the sourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceType(String value) {
        this.sourceType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="mapping" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="domain"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element ref="{}source_node"/&gt;
     *                             &lt;element name="target_node" type="{}domain_target_nodeType"/&gt;
     *                             &lt;element name="comments" type="{}commentsType" minOccurs="0"/&gt;
     *                           &lt;/sequence&gt;
     *                           &lt;attribute name="repeated" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="link" maxOccurs="unbounded" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="path"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="source_relation" type="{}source_relationType"/&gt;
     *                                       &lt;element name="target_relation" type="{}target_relationType"/&gt;
     *                                       &lt;element name="comments" type="{}commentsType" minOccurs="0"/&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                             &lt;element name="range"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element ref="{}source_node"/&gt;
     *                                       &lt;element name="target_node" type="{}range_target_nodeType"/&gt;
     *                                       &lt;element name="comments" type="{}commentsType" minOccurs="0"/&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mapping"
    })
    public static class Mappings {

        @XmlElement(required = true)
        protected List<X3ML.Mappings.Mapping> mapping;

        /**
         * Gets the value of the mapping property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the mapping property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMapping().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link X3ML.Mappings.Mapping }
         * 
         * 
         */
        public List<X3ML.Mappings.Mapping> getMapping() {
            if (mapping == null) {
                mapping = new ArrayList<X3ML.Mappings.Mapping>();
            }
            return this.mapping;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="domain"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element ref="{}source_node"/&gt;
         *                   &lt;element name="target_node" type="{}domain_target_nodeType"/&gt;
         *                   &lt;element name="comments" type="{}commentsType" minOccurs="0"/&gt;
         *                 &lt;/sequence&gt;
         *                 &lt;attribute name="repeated" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="link" maxOccurs="unbounded" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="path"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="source_relation" type="{}source_relationType"/&gt;
         *                             &lt;element name="target_relation" type="{}target_relationType"/&gt;
         *                             &lt;element name="comments" type="{}commentsType" minOccurs="0"/&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                   &lt;element name="range"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element ref="{}source_node"/&gt;
         *                             &lt;element name="target_node" type="{}range_target_nodeType"/&gt;
         *                             &lt;element name="comments" type="{}commentsType" minOccurs="0"/&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "domain",
            "link"
        })
        public static class Mapping {

            @XmlElement(required = true)
            protected X3ML.Mappings.Mapping.Domain domain;
            protected List<X3ML.Mappings.Mapping.Link> link;

            /**
             * Gets the value of the domain property.
             * 
             * @return
             *     possible object is
             *     {@link X3ML.Mappings.Mapping.Domain }
             *     
             */
            public X3ML.Mappings.Mapping.Domain getDomain() {
                return domain;
            }

            /**
             * Sets the value of the domain property.
             * 
             * @param value
             *     allowed object is
             *     {@link X3ML.Mappings.Mapping.Domain }
             *     
             */
            public void setDomain(X3ML.Mappings.Mapping.Domain value) {
                this.domain = value;
            }

            /**
             * Gets the value of the link property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the link property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getLink().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link X3ML.Mappings.Mapping.Link }
             * 
             * 
             */
            public List<X3ML.Mappings.Mapping.Link> getLink() {
                if (link == null) {
                    link = new ArrayList<X3ML.Mappings.Mapping.Link>();
                }
                return this.link;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element ref="{}source_node"/&gt;
             *         &lt;element name="target_node" type="{}domain_target_nodeType"/&gt;
             *         &lt;element name="comments" type="{}commentsType" minOccurs="0"/&gt;
             *       &lt;/sequence&gt;
             *       &lt;attribute name="repeated" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "sourceNode",
                "targetNode",
                "comments"
            })
            public static class Domain {

                @XmlElement(name = "source_node", required = true)
                protected String sourceNode;
                @XmlElement(name = "target_node", required = true)
                protected DomainTargetNodeType targetNode;
                protected CommentsType comments;
                @XmlAttribute(name = "repeated")
                @XmlSchemaType(name = "anySimpleType")
                protected String repeated;
                
                
                

                public Domain() {}

				public Domain(String sourceNode, DomainTargetNodeType targetNode) {
					this.sourceNode = sourceNode;
					this.targetNode = targetNode;
				}

				/**
                 * Gets the value of the sourceNode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSourceNode() {
                    return sourceNode;
                }

                /**
                 * Sets the value of the sourceNode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSourceNode(String value) {
                    this.sourceNode = value;
                }

                /**
                 * Gets the value of the targetNode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link DomainTargetNodeType }
                 *     
                 */
                public DomainTargetNodeType getTargetNode() {
                    return targetNode;
                }

                /**
                 * Sets the value of the targetNode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link DomainTargetNodeType }
                 *     
                 */
                public void setTargetNode(DomainTargetNodeType value) {
                    this.targetNode = value;
                }

                /**
                 * Gets the value of the comments property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link CommentsType }
                 *     
                 */
                public CommentsType getComments() {
                    return comments;
                }

                /**
                 * Sets the value of the comments property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link CommentsType }
                 *     
                 */
                public void setComments(CommentsType value) {
                    this.comments = value;
                }

                /**
                 * Gets the value of the repeated property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRepeated() {
                    return repeated;
                }

                /**
                 * Sets the value of the repeated property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRepeated(String value) {
                    this.repeated = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="path"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="source_relation" type="{}source_relationType"/&gt;
             *                   &lt;element name="target_relation" type="{}target_relationType"/&gt;
             *                   &lt;element name="comments" type="{}commentsType" minOccurs="0"/&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *         &lt;element name="range"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element ref="{}source_node"/&gt;
             *                   &lt;element name="target_node" type="{}range_target_nodeType"/&gt;
             *                   &lt;element name="comments" type="{}commentsType" minOccurs="0"/&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "path",
                "range"
            })
            public static class Link {

                @XmlElement(required = true)
                protected X3ML.Mappings.Mapping.Link.Path path;
                @XmlElement(required = true)
                protected X3ML.Mappings.Mapping.Link.Range range;

                /**
                 * Gets the value of the path property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link X3ML.Mappings.Mapping.Link.Path }
                 *     
                 */
                public X3ML.Mappings.Mapping.Link.Path getPath() {
                    return path;
                }

                /**
                 * Sets the value of the path property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link X3ML.Mappings.Mapping.Link.Path }
                 *     
                 */
                public void setPath(X3ML.Mappings.Mapping.Link.Path value) {
                    this.path = value;
                }

                /**
                 * Gets the value of the range property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link X3ML.Mappings.Mapping.Link.Range }
                 *     
                 */
                public X3ML.Mappings.Mapping.Link.Range getRange() {
                    return range;
                }

                /**
                 * Sets the value of the range property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link X3ML.Mappings.Mapping.Link.Range }
                 *     
                 */
                public void setRange(X3ML.Mappings.Mapping.Link.Range value) {
                    this.range = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="source_relation" type="{}source_relationType"/&gt;
                 *         &lt;element name="target_relation" type="{}target_relationType"/&gt;
                 *         &lt;element name="comments" type="{}commentsType" minOccurs="0"/&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "sourceRelation",
                    "targetRelation",
                    "comments"
                })
                public static class Path {

                    @XmlElement(name = "source_relation", required = true)
                    protected SourceRelationType sourceRelation;
                    @XmlElement(name = "target_relation", required = true)
                    protected TargetRelationType targetRelation;
                    protected CommentsType comments;

                    /**
                     * Gets the value of the sourceRelation property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link SourceRelationType }
                     *     
                     */
                    public SourceRelationType getSourceRelation() {
                        return sourceRelation;
                    }

                    /**
                     * Sets the value of the sourceRelation property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link SourceRelationType }
                     *     
                     */
                    public void setSourceRelation(SourceRelationType value) {
                        this.sourceRelation = value;
                    }

                    /**
                     * Gets the value of the targetRelation property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link TargetRelationType }
                     *     
                     */
                    public TargetRelationType getTargetRelation() {
                        return targetRelation;
                    }

                    /**
                     * Sets the value of the targetRelation property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link TargetRelationType }
                     *     
                     */
                    public void setTargetRelation(TargetRelationType value) {
                        this.targetRelation = value;
                    }

                    /**
                     * Gets the value of the comments property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link CommentsType }
                     *     
                     */
                    public CommentsType getComments() {
                        return comments;
                    }

                    /**
                     * Sets the value of the comments property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link CommentsType }
                     *     
                     */
                    public void setComments(CommentsType value) {
                        this.comments = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element ref="{}source_node"/&gt;
                 *         &lt;element name="target_node" type="{}range_target_nodeType"/&gt;
                 *         &lt;element name="comments" type="{}commentsType" minOccurs="0"/&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "sourceNode",
                    "targetNode",
                    "comments"
                })
                public static class Range {

                    @XmlElement(name = "source_node", required = true)
                    protected String sourceNode;
                    @XmlElement(name = "target_node", required = true)
                    protected RangeTargetNodeType targetNode;
                    protected CommentsType comments;

                    /**
                     * Gets the value of the sourceNode property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getSourceNode() {
                        return sourceNode;
                    }

                    /**
                     * Sets the value of the sourceNode property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setSourceNode(String value) {
                        this.sourceNode = value;
                    }

                    /**
                     * Gets the value of the targetNode property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link RangeTargetNodeType }
                     *     
                     */
                    public RangeTargetNodeType getTargetNode() {
                        return targetNode;
                    }

                    /**
                     * Sets the value of the targetNode property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link RangeTargetNodeType }
                     *     
                     */
                    public void setTargetNode(RangeTargetNodeType value) {
                        this.targetNode = value;
                    }

                    /**
                     * Gets the value of the comments property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link CommentsType }
                     *     
                     */
                    public CommentsType getComments() {
                        return comments;
                    }

                    /**
                     * Sets the value of the comments property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link CommentsType }
                     *     
                     */
                    public void setComments(CommentsType value) {
                        this.comments = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="namespace" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="prefix" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *                 &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "namespace"
    })
    public static class Namespaces {

        @XmlElement(required = true)
        protected List<X3ML.Namespaces.Namespace> namespace;

        /**
         * Gets the value of the namespace property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the namespace property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNamespace().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link X3ML.Namespaces.Namespace }
         * 
         * 
         */
        public List<X3ML.Namespaces.Namespace> getNamespace() {
            if (namespace == null) {
                namespace = new ArrayList<X3ML.Namespaces.Namespace>();
            }
            return this.namespace;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="prefix" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
         *       &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Namespace {

            @XmlAttribute(name = "prefix", required = true)
            @XmlSchemaType(name = "anySimpleType")
            protected String prefix;
            @XmlAttribute(name = "uri", required = true)
            @XmlSchemaType(name = "anySimpleType")
            protected String uri;
            
            public Namespace(){}            

            public Namespace(String prefix, String uri) {
				this.prefix = prefix;
				this.uri = uri;
			}



			/**
             * Gets the value of the prefix property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrefix() {
                return prefix;
            }

            /**
             * Sets the value of the prefix property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrefix(String value) {
                this.prefix = value;
            }

            /**
             * Gets the value of the uri property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUri() {
                return uri;
            }

            /**
             * Sets the value of the uri property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUri(String value) {
                this.uri = value;
            }

        }

    }

}
